// This file contains all searchable content for Algolia indexing
export const searchableContent = [
  // Homepage
  {
    objectID: 'home',
    title: 'Foxes Technology - Tour & Activity Booking Platform',
    description: 'The all-in-one platform for tour operators and activity providers in Egypt and the GCC. Streamline bookings, payments, and operations.',
    content: 'Transform your tour and activity business with our comprehensive booking platform. Features include online booking, POS systems, kiosks, mobile apps, AI assistant, and analytics.',
    url: '/',
    category: 'company',
    tags: ['booking', 'tours', 'activities', 'platform', 'egypt', 'gcc'],
    image: '/images/hero-image.jpg'
  },

  // Solutions
  {
    objectID: 'solution-online-booking',
    title: 'Online Booking System',
    description: 'Accept bookings 24/7 with our intelligent online booking system',
    content: 'Powerful online booking system that works 24/7. Real-time availability, instant confirmations, automated emails, secure payments, multi-language support, and mobile-responsive design.',
    url: '/solutions/online-booking',
    category: 'solutions',
    tags: ['booking', 'online', 'reservations', '24/7', 'automation'],
    image: '/images/online-booking.jpg'
  },
  {
    objectID: 'solution-pos-hardware',
    title: 'POS Hardware & Handheld Devices',
    description: 'Professional point-of-sale systems for on-site bookings and check-ins',
    content: 'Complete POS hardware solution with handheld devices, tablets, and terminals. Perfect for on-site bookings, ticket scanning, and customer check-ins. Works offline with automatic sync.',
    url: '/solutions/pos-hardware',
    category: 'solutions',
    tags: ['pos', 'hardware', 'handheld', 'terminal', 'offline'],
    image: '/images/pos-device.jpg'
  },
  {
    objectID: 'solution-kiosk',
    title: 'Self-Service Kiosks',
    description: 'Automated kiosks for contactless bookings and check-ins',
    content: 'Self-service kiosk systems that allow customers to book, pay, and check-in without staff assistance. Reduce queues, increase efficiency, and provide 24/7 service. Supports multiple payment methods and languages.',
    url: '/solutions/kiosk',
    category: 'solutions',
    tags: ['kiosk', 'self-service', 'contactless', 'automation', 'check-in'],
    image: '/images/kiosk.jpg'
  },
  {
    objectID: 'solution-mobile-apps',
    title: 'Mobile Apps',
    description: 'Native iOS and Android apps for customers and staff',
    content: 'Custom-branded mobile applications for both customers and staff. Customer app features booking, tickets, and trip planning. Staff app includes check-ins, inventory management, and real-time updates.',
    url: '/solutions',
    category: 'solutions',
    tags: ['mobile', 'app', 'ios', 'android', 'native'],
    image: '/images/mobile-apps.jpg'
  },
  {
    objectID: 'solution-ai',
    title: 'AI Assistant & Automation',
    description: 'AI-powered chatbot and smart automation for customer service',
    content: 'Intelligent AI assistant that handles customer inquiries 24/7, provides personalized recommendations, automates responses, and learns from interactions. Supports multiple languages and integrates with WhatsApp, Facebook, and your website.',
    url: '/solutions/ai',
    category: 'solutions',
    tags: ['ai', 'artificial intelligence', 'chatbot', 'automation', 'customer service'],
    image: '/images/ai-assistant.jpg'
  },
  {
    objectID: 'solution-analytics',
    title: 'Analytics & Reporting',
    description: 'Comprehensive analytics and business intelligence dashboards',
    content: 'Advanced analytics platform with real-time dashboards, sales reports, customer insights, revenue forecasting, and performance metrics. Make data-driven decisions with powerful visualizations and custom reports.',
    url: '/solutions/analytics',
    category: 'solutions',
    tags: ['analytics', 'reporting', 'dashboard', 'insights', 'business intelligence'],
    image: '/images/analytics.jpg'
  },

  // Features Page
  {
    objectID: 'features',
    title: 'All Features - Everything You Need',
    description: 'Complete feature set for tour operators: 100+ features including booking, payments, CRM, analytics, and 50+ integrations',
    content: 'Comprehensive platform features: online booking 24/7, all payment methods, customer management, inventory tracking, staff management, real-time analytics, POS hardware, AI assistant, and integrations with QuickBooks, Stripe, WhatsApp, and 50+ other tools.',
    url: '/features',
    category: 'features',
    tags: ['features', 'complete', 'all-in-one', 'comprehensive', 'platform'],
    image: '/images/features.jpg'
  },

  // Individual Features
  {
    objectID: 'feature-real-time-booking',
    title: 'Real-time Availability & Booking',
    description: 'Live inventory management with instant booking confirmations',
    content: 'Real-time availability tracking ensures no overbookings. Customers see live availability and get instant confirmations.',
    url: '/features',
    category: 'features',
    tags: ['real-time', 'availability', 'inventory', 'instant'],
  },
  {
    objectID: 'feature-payment-processing',
    title: 'Secure Payment Processing',
    description: 'Accept all major payment methods with PCI-compliant security',
    content: 'Integrated payment processing supporting credit cards, digital wallets, bank transfers, and local payment methods. PCI-DSS compliant with fraud protection.',
    url: '/features',
    category: 'features',
    tags: ['payment', 'secure', 'credit card', 'wallet', 'pci'],
  },
  {
    objectID: 'feature-multi-language',
    title: 'Multi-language Support',
    description: 'Serve international customers in their preferred language',
    content: 'Full multi-language support including Arabic, English, French, German, Russian, and Chinese. Automatic translation and localization.',
    url: '/features',
    category: 'features',
    tags: ['language', 'translation', 'international', 'arabic', 'english'],
  },
  {
    objectID: 'feature-automated-emails',
    title: 'Automated Email & SMS',
    description: 'Automated communication with customers at every step',
    content: 'Automated booking confirmations, reminders, receipts, and follow-ups via email and SMS. Customizable templates in multiple languages.',
    url: '/features',
    category: 'features',
    tags: ['email', 'sms', 'automation', 'communication', 'notifications'],
  },
  {
    objectID: 'feature-customer-management',
    title: 'Customer Relationship Management',
    description: 'Complete CRM for managing customer data and relationships',
    content: 'Built-in CRM to track customer history, preferences, special requests, and loyalty. Segment customers and run targeted marketing campaigns.',
    url: '/features',
    category: 'features',
    tags: ['crm', 'customers', 'relationships', 'loyalty', 'marketing'],
  },
  {
    objectID: 'feature-channel-manager',
    title: 'Channel Manager Integration',
    description: 'Connect with OTAs and distribution channels',
    content: 'Integrate with major OTAs like Viator, GetYourGuide, Expedia, and more. Centralized inventory and pricing management across all channels.',
    url: '/features',
    category: 'features',
    tags: ['channel manager', 'ota', 'distribution', 'viator', 'integration'],
  },
  {
    objectID: 'feature-reviews-ratings',
    title: 'Reviews & Ratings Management',
    description: 'Collect and showcase customer reviews',
    content: 'Automated review collection, rating display, and reputation management. Integrates with TripAdvisor, Google Reviews, and social platforms.',
    url: '/features',
    category: 'features',
    tags: ['reviews', 'ratings', 'reputation', 'tripadvisor', 'testimonials'],
  },
  {
    objectID: 'feature-dynamic-pricing',
    title: 'Dynamic Pricing & Promotions',
    description: 'Smart pricing rules and promotional campaigns',
    content: 'Set up dynamic pricing based on demand, season, or occupancy. Create discount codes, early bird offers, group discounts, and flash sales.',
    url: '/features',
    category: 'features',
    tags: ['pricing', 'promotions', 'discounts', 'dynamic', 'revenue management'],
  },

  // Pricing
  {
    objectID: 'pricing',
    title: 'Pricing Plans',
    description: 'Flexible pricing for businesses of all sizes',
    content: 'Choose from Starter, Professional, or Enterprise plans. All plans include core features with scalable options. No setup fees, cancel anytime.',
    url: '/pricing',
    category: 'pricing',
    tags: ['pricing', 'plans', 'cost', 'subscription', 'packages'],
  },
  {
    objectID: 'pricing-starter',
    title: 'Starter Plan',
    description: 'Perfect for small tour operators getting started',
    content: 'Starter plan at $99/month includes online booking, up to 100 bookings/month, mobile apps, basic analytics, and email support. Ideal for new businesses.',
    url: '/pricing',
    category: 'pricing',
    tags: ['starter', 'small business', 'affordable', 'basic'],
  },
  {
    objectID: 'pricing-professional',
    title: 'Professional Plan',
    description: 'For growing tour operators with advanced needs',
    content: 'Professional plan at $299/month includes unlimited bookings, POS hardware, AI assistant, advanced analytics, priority support, and custom branding. Most popular choice.',
    url: '/pricing',
    category: 'pricing',
    tags: ['professional', 'growing', 'unlimited', 'advanced'],
  },
  {
    objectID: 'pricing-enterprise',
    title: 'Enterprise Plan',
    description: 'Custom solutions for large tour operators',
    content: 'Enterprise plan with custom pricing includes white-label solution, dedicated account manager, API access, custom integrations, SLA guarantees, and 24/7 support.',
    url: '/pricing',
    category: 'pricing',
    tags: ['enterprise', 'custom', 'white-label', 'dedicated'],
  },

  // Company
  {
    objectID: 'about',
    title: 'About Foxes Technology',
    description: 'Learn about our mission to revolutionize tour and activity bookings',
    content: 'Foxes Technology is transforming how tour operators and activity providers manage their business in Egypt and the GCC. Our mission is to make booking technology accessible, powerful, and affordable for businesses of all sizes.',
    url: '/about',
    category: 'company',
    tags: ['about', 'company', 'mission', 'team', 'story'],
  },
  {
    objectID: 'contact',
    title: 'Contact Us',
    description: 'Get in touch with our team',
    content: 'Contact Foxes Technology for demos, support, or partnership inquiries. Offices in Cairo, Dubai, and Riyadh. Email: hello@foxestechnology.com',
    url: '/contact',
    category: 'company',
    tags: ['contact', 'support', 'demo', 'email', 'phone'],
  },
  {
    objectID: 'careers',
    title: 'Careers at Foxes Technology',
    description: 'Join our team and build the future of travel technology',
    content: 'Work with us to revolutionize the tour and activity industry. We are hiring software engineers, product managers, sales professionals, and customer success specialists.',
    url: '/careers',
    category: 'company',
    tags: ['careers', 'jobs', 'hiring', 'team', 'employment'],
  },
  {
    objectID: 'careers-apply',
    title: 'Apply for a Job at Foxes Technology',
    description: 'Submit your application to join our team',
    content: 'Apply for open positions at Foxes Technology. Submit your resume, cover letter, and contact information. We are looking for talented engineers, designers, sales professionals, and more to build the future of travel technology.',
    url: '/careers/apply',
    category: 'company',
    tags: ['apply', 'application', 'job application', 'careers', 'resume', 'submit'],
  },

  // Resources
  {
    objectID: 'documentation',
    title: 'Documentation',
    description: 'Comprehensive guides and API references',
    content: 'Complete documentation for Foxes Technology booking and POS software. Includes implementation guides, API reference, tutorials, security best practices, and integration guides. SDKs available in multiple languages for custom development.',
    url: '/docs',
    category: 'resources',
    tags: ['documentation', 'docs', 'guides', 'api', 'sdk', 'tutorial', 'implementation'],
  },
  {
    objectID: 'api-reference',
    title: 'API Reference',
    description: 'RESTful API documentation for custom integrations',
    content: 'Complete API v2.0 reference for Foxes Technology booking platform. Authentication, Activities API, Bookings API, Payments API, Contacts API, Settings API. RESTful endpoints with code examples in cURL, JavaScript, Python, and PHP. API key authentication, HTTPS encrypted, UNIX Epoch time format. Rate limits available.',
    url: '/api',
    category: 'resources',
    tags: ['api', 'reference', 'rest', 'webhooks', 'sdk', 'integration', 'development', 'endpoints', 'authentication'],
  },
  {
    objectID: 'support-center',
    title: 'Support Center',
    description: '24/7 support for software customers',
    content: 'Get help with your Foxes Technology software. 24/7 live chat, email support, phone support, and video calls. Technical support included with all packages. Knowledge base, community forum, and video tutorials available. 99.98% system uptime.',
    url: '/support',
    category: 'resources',
    tags: ['support', 'help', 'chat', 'phone', 'email', '24/7', 'customer service', 'technical'],
  },
  {
    objectID: 'get-started',
    title: 'Implementation Guide',
    description: 'Implement your system in 3 steps',
    content: 'Complete implementation guide for Foxes Technology software. Purchase and consultation, professional installation and setup by our team, comprehensive staff training, and go live. Includes on-premise, cloud, or hybrid deployment options. Full ownership and control of your system.',
    url: '/get-started',
    category: 'resources',
    tags: ['get started', 'implementation', 'installation', 'setup', 'launch', 'deployment', 'training'],
  },
  {
    objectID: 'privacy-policy',
    title: 'Privacy Policy',
    description: 'How we protect and handle your data',
    content: 'Our privacy policy explains how we collect, use, and protect your personal information. GDPR compliant with industry-standard security.',
    url: '/privacy-policy',
    category: 'resources',
    tags: ['privacy', 'policy', 'gdpr', 'data protection', 'legal'],
  },
  {
    objectID: 'terms-of-service',
    title: 'Terms of Service',
    description: 'Terms and conditions for using our platform',
    content: 'Terms of service and user agreement for Foxes Technology platform. Covers usage rights, responsibilities, and service level agreements.',
    url: '/terms-of-service',
    category: 'resources',
    tags: ['terms', 'service', 'agreement', 'legal', 'conditions'],
  },
  {
    objectID: 'cookie-policy',
    title: 'Cookie Policy',
    description: 'How we use cookies and tracking technologies',
    content: 'Cookie policy explaining how we use cookies to improve user experience, analytics, and personalization. Manage your cookie preferences.',
    url: '/cookie-policy',
    category: 'resources',
    tags: ['cookies', 'tracking', 'privacy', 'preferences'],
  },
  {
    objectID: 'refund-policy',
    title: 'Refund Policy',
    description: 'Our refund and cancellation policy',
    content: 'Refund policy for Foxes Technology subscription services. 30-day money-back guarantee for new customers. Flexible cancellation terms.',
    url: '/refund-policy',
    category: 'resources',
    tags: ['refund', 'cancellation', 'money-back', 'guarantee'],
  },

  // FAQs
  {
    objectID: 'faq-setup',
    title: 'How long does setup take?',
    description: 'Getting started with Foxes Technology',
    content: 'Setup typically takes 2-5 business days. We provide full onboarding support, data migration, training, and testing before going live.',
    url: '/#faq',
    category: 'resources',
    tags: ['faq', 'setup', 'onboarding', 'implementation'],
  },
  {
    objectID: 'faq-integration',
    title: 'Does it integrate with my existing tools?',
    description: 'Integration capabilities',
    content: 'Yes, we integrate with QuickBooks, Xero, Mailchimp, WhatsApp, Facebook, Google Calendar, and hundreds more through our API and Zapier integration.',
    url: '/#faq',
    category: 'resources',
    tags: ['faq', 'integration', 'api', 'zapier', 'tools'],
  },
  {
    objectID: 'faq-mobile',
    title: 'Do I get mobile apps?',
    description: 'Mobile application availability',
    content: 'Yes, all plans include custom-branded mobile apps for iOS and Android. Both customer-facing and staff management apps are included.',
    url: '/#faq',
    category: 'resources',
    tags: ['faq', 'mobile', 'apps', 'ios', 'android'],
  },
  {
    objectID: 'faq-support',
    title: 'What kind of support do you offer?',
    description: 'Customer support options',
    content: 'We offer email support (all plans), priority support (Professional+), and 24/7 phone support (Enterprise). Plus comprehensive documentation, video tutorials, and live training sessions.',
    url: '/#faq',
    category: 'resources',
    tags: ['faq', 'support', 'help', 'training', 'documentation'],
  },
  {
    objectID: 'faq-languages',
    title: 'What languages are supported?',
    description: 'Multi-language capabilities',
    content: 'Platform supports Arabic, English, French, German, Russian, Chinese, Spanish, and Italian. Admin panel is available in Arabic and English.',
    url: '/#faq',
    category: 'resources',
    tags: ['faq', 'languages', 'translation', 'arabic', 'english'],
  },

  // Operator landing pages
  {
    objectID: 'operators-tour-agencies-en',
    title: 'Booking Software for Tour Agencies in Egypt',
    description: 'Built for multi-product tour agencies in Cairo, Hurghada, Luxor and Aswan. Manage 100+ products, sync OTAs, generate branded vouchers, and cut commissions in half.',
    content: 'Foxes Technology for tour agencies. Multi-product manager for tours, transfers, attractions, packages. White-label voucher generator. B2B reseller portal with commission tracking. Channel manager for Viator, GetYourGuide, TripAdvisor, Klook. Multi-currency invoicing. Customer database with rebooking flows. Free for 30 days, no setup fee, full Arabic support.',
    url: '/operators/tour-agencies',
    category: 'solutions',
    tags: ['tour agency', 'travel agency', 'cairo', 'hurghada', 'luxor', 'aswan', 'multi-product', 'channel manager', 'voucher', 'b2b', 'reseller'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-tour-agencies-ar',
    title: 'برنامج حجوزات لوكالات السياحة في مصر',
    description: 'مصمم لوكالات السياحة متعددة المنتجات في القاهرة والغردقة والأقصر وأسوان — أدر 100+ منتج، زامن OTAs، وأنشئ قسائم احترافية، وخفّض العمولات إلى النصف.',
    content: 'Foxes Technology لوكالات السياحة. مدير منتجات متعددة للجولات والنقل والمعالم والباقات. منشئ قسائم بعلامتك التجارية. بوابة B2B للموزعين مع تتبع العمولات. مدير قنوات Viator و GetYourGuide و TripAdvisor و Klook. فواتير متعددة العملات. قاعدة عملاء مع تدفق إعادة الحجز. مجاني 30 يوم، بدون رسوم تركيب، دعم كامل بالعربية.',
    url: '/ar/operators/tour-agencies',
    category: 'solutions',
    tags: ['وكالة سياحة', 'القاهرة', 'الغردقة', 'الأقصر', 'أسوان', 'منتجات متعددة', 'قسائم', 'موزعين'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-water-sports-en',
    title: 'Booking Software for Water Sports Operators in Egypt',
    description: 'Built for jet ski, parasailing, kitesurfing, paddleboard and banana boat operators. Sell sessions while you sleep with hourly slots, digital waivers, and live equipment tracking.',
    content: 'Foxes Technology for water sports activity providers. Hourly slot booking with capacity caps. Digital waiver signing on customer phone before arrival. Live equipment availability for jet skis, kayaks, paddleboards, parasails. Group and bachelor party packages. Insurance-ready record-keeping. Beach pickup logistics with auto-reminder SMS. Free for 30 days, no setup fee, full Arabic support. Hurghada, Sharm, Sahel, Marsa Alam, Dahab.',
    url: '/operators/water-sports',
    category: 'solutions',
    tags: ['water sports', 'jet ski', 'parasailing', 'kitesurfing', 'paddleboard', 'banana boat', 'hurghada', 'sharm', 'sahel', 'waiver', 'beach activities'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-water-sports-ar',
    title: 'برنامج حجوزات لمشغلي الرياضات المائية في مصر',
    description: 'مصمم لمشغلي الجت سكي والباراسيلينج والكايت سيرف والباناناـبوت — بِع جلسات أثناء نومك بمواعيد بالساعة وتنازلات رقمية وتتبع معدات فوري.',
    content: 'Foxes Technology لمشغلي الرياضات المائية. حجز مواعيد بالساعة مع حدود سعة. توقيع تنازلات رقمية على هاتف العميل قبل الوصول. توفر فوري لمعدات الجت سكي والكاياك والبادل بورد والباراسيل. باقات مجموعات وحفلات. سجلات جاهزة للتأمين. لوجستيات الالتقاط من الشاطئ مع SMS تذكير. مجاني 30 يوم، دعم كامل بالعربية. الغردقة، شرم، الساحل، مرسى علم، دهب.',
    url: '/ar/operators/water-sports',
    category: 'solutions',
    tags: ['رياضات مائية', 'جت سكي', 'باراسيلينج', 'كايت سيرف', 'بادل بورد', 'الغردقة', 'شرم', 'الساحل', 'تنازل'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-boat-operators-en',
    title: 'Booking Software for Boat Operators in Egypt',
    description: 'Built for private charter, speedboat tour, fishing and sunset cruise operators. Stop double-bookings, get paid before they board, and handle weather cancellations cleanly.',
    content: 'Foxes Technology for boat charter and tour operators. Live vessel calendar across one boat or a fleet. Deposit and balance schedule with auto-reminders. Captain and crew assignment with overlap detection. Weather cancellation automation with one-click rebooking. Multi-channel payments via Stripe, Paymob, Fawry, Vodafone Cash, Instapay, bank transfer. Customer database with repeat-charter flows. Free for 30 days, no setup fee, full Arabic support. Hurghada, Sharm, Marina, El Gouna, Dahab.',
    url: '/operators/boat-operators',
    category: 'solutions',
    tags: ['boat operator', 'charter', 'speedboat', 'fishing trip', 'sunset cruise', 'yacht', 'hurghada', 'sharm', 'el gouna', 'marina', 'vessel calendar'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-boat-operators-ar',
    title: 'برنامج حجوزات لمشغلي القوارب في مصر',
    description: 'مصمم لمشغلي القوارب الخاصة وقوارب السرعة ورحلات الصيد ورحلات الغروب — أوقف الحجز المزدوج، احصل على دفعتك قبل الإقلاع، وتعامل مع إلغاءات الطقس بسلاسة.',
    content: 'Foxes Technology لمشغلي قوارب التأجير والجولات. تقويم سفن مباشر لقارب واحد أو أسطول. جدول دفعات مقدمة وأرصدة مع تذكيرات تلقائية. تعيين الكابتن والطاقم مع كشف التداخل. أتمتة إلغاءات الطقس مع إعادة حجز بنقرة واحدة. مدفوعات متعددة القنوات عبر Stripe و Paymob و Fawry و Vodafone Cash و Instapay والتحويل البنكي. قاعدة عملاء مع تدفقات إعادة التأجير. مجاني 30 يوم، دعم كامل بالعربية. الغردقة، شرم، المارينا، الجونة، دهب.',
    url: '/ar/operators/boat-operators',
    category: 'solutions',
    tags: ['قوارب', 'تأجير', 'قارب سرعة', 'رحلة صيد', 'رحلة غروب', 'يخت', 'الغردقة', 'شرم', 'الجونة', 'مارينا'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-dinner-cruises-en',
    title: 'Booking Software for Dinner Cruise Operators in Egypt',
    description: 'Built for Nile dinner cruise and Hurghada dinner boat operators — fill every seat, manage timeslots and F&B, and cut OTA fees in half.',
    content: 'Foxes Technology for dinner cruise operators. Direct booking engine, smart seating and capacity management, group bookings with deposits, F&B add-ons, dock pickup logistics, dynamic seasonal pricing, manifest export for chef, OTA channel manager, multi-boat fleet support. Free for 30 days, no setup fee, full Arabic support. Cairo, Luxor, Aswan, Hurghada.',
    url: '/operators/dinner-cruises',
    category: 'solutions',
    tags: ['dinner cruise', 'nile cruise', 'felucca', 'cairo', 'luxor', 'aswan', 'hurghada', 'booking software', 'operator', 'restaurant boat'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-dinner-cruises-ar',
    title: 'برنامج حجوزات لمشغلي رحلات العشاء النيلية في مصر',
    description: 'مصمم لمشغلي رحلات العشاء النيلية وقوارب العشاء في الغردقة — املأ كل مقعد، أدر المواعيد والطعام، وخفّض عمولات OTA إلى النصف.',
    content: 'Foxes Technology لمشغلي رحلات العشاء. محرك حجوزات مباشر، إدارة ذكية للمقاعد والسعة، حجوزات المجموعات بدفعات مقدمة، إضافات الطعام، لوجستيات الرصيف، تسعير موسمي ديناميكي، تصدير قائمة المطبخ، إدارة قنوات OTA، دعم الأسطول. مجاني 30 يوم، بدون رسوم تركيب، دعم كامل بالعربية.',
    url: '/ar/operators/dinner-cruises',
    category: 'solutions',
    tags: ['رحلة عشاء', 'رحلة نيلية', 'فلوكا', 'القاهرة', 'الأقصر', 'أسوان', 'الغردقة', 'حجوزات'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-diving-centres-en',
    title: 'Booking Software for Diving Centres in Egypt',
    description: 'Built for dive operators in Hurghada, Sharm, Marsa Alam and Dahab — manage PADI/SSI certs, equipment rentals, and multi-day courses in one place.',
    content: 'Foxes Technology for diving centres. PADI and SSI certification verification, equipment rental tracking, multi-day course scheduling, divemaster shift planning, dive site catalog, group bookings, liveaboards, and dive log integration. Free for 30 days, no setup fee, full Arabic support.',
    url: '/operators/diving-centres',
    category: 'solutions',
    tags: ['diving', 'dive centre', 'padi', 'ssi', 'hurghada', 'sharm', 'marsa alam', 'dahab', 'booking software', 'operator'],
    image: '/og-image.png',
  },
  {
    objectID: 'operators-diving-centres-ar',
    title: 'برنامج حجوزات لمراكز الغوص في مصر',
    description: 'مصمم لمراكز الغوص في الغردقة وشرم الشيخ ومرسى علم ودهب — إدارة شهادات PADI و SSI وإيجار المعدات والدورات في مكان واحد.',
    content: 'Foxes Technology لمراكز الغوص. التحقق من شهادات PADI و SSI، تتبع إيجار المعدات، جدولة الدورات متعددة الأيام، تخطيط ورديات مدربي الغوص، كتالوج مواقع الغوص، الحجوزات الجماعية، قوارب الإقامة، تكامل سجل الغوص. مجاني لمدة 30 يوم، بدون رسوم تركيب، دعم كامل بالعربية.',
    url: '/ar/operators/diving-centres',
    category: 'solutions',
    tags: ['غوص', 'مركز غوص', 'padi', 'ssi', 'الغردقة', 'شرم الشيخ', 'مرسى علم', 'دهب', 'حجوزات'],
    image: '/og-image.png',
  },
];
